# List of unclaimed Storage Volumes from a specified cluster in VPLEX
---
- name: List of unclaimed Storage Volumes from a specified cluster in VPLEX
  hosts: localhost
  connection: local

  vars_files:
    - vars/connection.yml
    - vars/credentials.yml

  vars:
    input: &connection_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"

  tasks:
    - name: Get list of all storage volumes in a given cluster
      dellemc_vplex_gatherfacts:
        <<: *connection_vars
        cluster_name: "{{ cluster_name }}"
        gather_subset:
          - stor_vol
      register: storage_volumes

    - name: Get details of all storage volumes
      dellemc_vplex_storage_volume:
        <<: *connection_vars
        cluster_name: "{{ cluster_name }}"
        storage_volume_name: "{{ item }}"
        get_itls: false
        state: present
      loop: "{{ storage_volumes.StorageVolumes }}"
      register: storage_vols

    - name: Set empty volumes list
      set_fact:
        volumes: []

    - name: Get unclaimed storage volumes
      set_fact:
        volumes: "{{ volumes + [item.storage_details.name] }}"
      no_log: true
      loop: "{{ storage_vols.results }}"
      when: item.storage_details.use == 'unclaimed'

    - debug:
        var: volumes
