# VPlex teardown

---
- name: Perform VPlex teardown
  hosts: localhost
  connection: local

  vars_files:
    - vars/connection.yml
    - vars/credentials.yml
    - vars/input_teardown.yml

  vars:
    input: &connection_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
    ddevice: []
    devices: []

  tasks:
    - name: Get the storage view
      dellemc_vplex_storage_view:
        <<: *connection_vars
        cluster_name: "{{ cluster_name }}"
        storage_view_name: "{{ storage_view_name }}"
        state: "present"
      register: storage_view

    - name: Fetch the virtual volume names
      set_fact:
        virtual_names: "{{ storage_view.storageview_details.virtual_volumes
          | map(attribute='uri') | list }}"

    - name: Delete the storage view
      dellemc_vplex_storage_view:
        <<: *connection_vars
        cluster_name: "{{ cluster_name }}"
        storage_view_name: "{{ storage_view_name }}"
        state: "absent"
      register: storage_view

    - name: Get details of the distributed virtual volumes
      dellemc_vplex_distributed_virtual_volume:
        <<: *connection_vars
        distributed_virtual_volume_name: "{{ item.split('/')[-1] }}"
        state: present
      loop: "{{ virtual_names[0:virtual_names|length] }}"
      register: virt_det

    - name: Fetch the distributed devices
      set_fact:
        dd_device: "{{ virt_det['results'] | map(attribute=
          'dist_vv_details.supporting_device') | list }}"

    - name: Get details of the distributed device
      dellemc_vplex_distributed_device:
        <<: *connection_vars
        distributed_device_name: "{{ item.split('/')[-1] }}"
        state: present
      loop: "{{ dd_device }}"
      register: device_det

    - name: Fetch the source and target devices
      set_fact:
        dev_list: "{{ device_det['results'] | map(attribute=
          'dist_device_details.devices') | list }}"

    - name: Combine the source and target devices into a single list
      set_fact:
        all_devices: "{{ ddevice }} + {{ item }}"
      loop: "{{ dev_list }}"

    - name: Delete the distributed virtual volume
      dellemc_vplex_distributed_virtual_volume:
        <<: *connection_vars
        distributed_virtual_volume_name: "{{ item.split('/')[-1] }}"
        state: absent
      loop: "{{ virtual_names[0:virtual_names|length] }}"
      register: delete_vv

    - name: Delete the distributed device
      dellemc_vplex_distributed_device:
        <<: *connection_vars
        distributed_device_name: "{{ item.split('/')[-1] }}"
        state: absent
      loop: "{{ dd_device }}"
      register: delete_dd

    - name: Delete the device
      include_role:
        name: removedevice
      vars:
        cluster_name: "{{ item.split('/')[-3] }}"
        devices: "{{ item.split('/')[-1] }}"
      loop: "{{ all_devices }}"
