---
- name: "Setup variables for remove device in tasks"
  set_fact:
    input: &conn_vars
      vplexhost: "{{ vplexhost }}"
      vplexuser: "{{ vplexuser }}"
      vplexpassword: "{{ vplexpassword }}"
      verifycert: "{{ verifycert }}"
    extents: []
    volumes: []

- name: Get list of extents
  dellemc_vplex_gatherfacts:
    <<: *conn_vars
    cluster_name: "{{ cluster_name }}"
    gather_subset:
      - extent
  register: ext_list

- name: Get details of extent
  dellemc_vplex_extent:
    <<: *conn_vars
    cluster_name: "{{ cluster_name }}"
    extent_name: "{{ line_item }}"
    state: "present"
  with_items: "{{ ext_list.Extents }}"
  loop_control:
    loop_var: line_item
  register: ext_det

- name: Get list of extents and storage volumes that matches the device
  set_fact:
    extents: "{{ extents + [line_item.extent_details.name] }}"
    volumes: "{{ volumes + [line_item.extent_details.storage_volume] }}"
  loop: "{{ ext_det.results }}"
  loop_control:
    loop_var: line_item
  when: (line_item.extent_details.used_by|length>0) and
        (line_item.extent_details.used_by[0].split('/')[-1] in devices)

- name: Delete the device
  dellemc_vplex_device:
    <<: *conn_vars
    cluster_name: "{{ cluster_name }}"
    device_name: "{{ devices }}"
    state: "absent"
  register: device_delete

- name: Delete the extent
  dellemc_vplex_extent:
    <<: *conn_vars
    cluster_name: "{{ cluster_name }}"
    extent_name: "{{ line_item }}"
    state: "absent"
  loop: "{{ extents }}"
  loop_control:
    loop_var: line_item
  register: extent_delete

- name: Unclaim the storage volume
  dellemc_vplex_storage_volume:
    <<: *conn_vars
    cluster_name: "{{ cluster_name }}"
    storage_volume_name: "{{ line_item.split('/')[-1] }}"
    claimed_state: "unclaimed"
    state: "present"
  loop: "{{ volumes }}"
  loop_control:
    loop_var: line_item
  register: unclaim_vol
